config/routes.rb
CoffeeLetter::Application.routes.draw do

  get "users/index"
  get "dashboard/index"

  get "signup"  => "users#new", :as => "signup"
  get "logout"  => "sessions#destroy", :as => "logout"
  get "login"   => "sessions#new", :as => "login"
  match 'admin' => 'admin/dashboard#index', :via => :get, :as => "admin" 
  
  resources :users, :only => [:create, :new]
  resources :sessions
  resources :letters, except: [:destroy, :index]
  resources :billings

  namespace :admin do
    resources :dashboard, only: [:index]
    resources :letters
    resources :billings, except: [:destroy]
    resources :users, except: [:destroy]
    resources :coupons, except: [:destroy]
    resources :products, except: [:destroy]
  end

  resources :users do
    scope module: :user do 
      resources :letters, except: [:destroy]
      resources :billings, except: [:destroy, :new]
      resources :main, only: [:index]
    end
  end

  get "main/index"
  root :to => 'main#index'
end

app/models/letter.rb
class Letter < ActiveRecord::Base
  attr_accessor :controller_name

  belongs_to :billing
  belongs_to :user
  
  before_create :letter_has_billing
  
  # validates_presence_of :sender_name
  private    
    def letter_has_billing
      self.create_billing(sender_name: self.sender_name)
    end
end

app/controllers/admin/letters_controller.rb
class Admin::LettersController < ApplicationController
  layout 'admin'
  def index
    @letters = Letter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @letters }
    end
  end

  # GET /letters/1
  # GET /letters/1.json
  def show
    @letter = Letter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @letter }
    end
  end

  # GET /letters/new
  # GET /letters/new.json
  def new
    @letter = Letter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @letter }
    end
  end

  # GET /letters/1/edit
  def edit
    @letter = Letter.find(params[:id])
  end

  # POST /letters
  # POST /letters.json
  def create
    @letter = Letter.new(params[:letter])    
    respond_to do |format|
      if @letter.save
        @letter.billings.create()
        if @letter.controller_name == 'main'
          format.html { redirect_to edit_letter_path(@letter) }
        else
          format.html { redirect_to @letter, notice: 'Letter was successfully created.' }
          format.json { render json: @letter, status: :created, location: @letter }
        end
      else
        format.html { render action: "new" }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /letters/1
  # PUT /letters/1.json
  def update
    @letter = Letter.find(params[:id])

    respond_to do |format|
      if @letter.update_attributes(params[:letter])
        format.html { redirect_to @letter, notice: 'Letter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /letters/1
  # DELETE /letters/1.json
  def destroy
    @letter = Letter.find(params[:id])
    @letter.destroy

    respond_to do |format|
      format.html { redirect_to letters_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/letters_controller.rb
#encoding: utf-8
class LettersController < ApplicationController
  before_filter :store_location
  # GET /letters
  # GET /letters.json
  def index
    @letters = Letter.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @letters }
    end
  end

  # GET /letters/1
  # GET /letters/1.json
  def show
    @letter = Letter.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @letter }
    end
  end

  # GET /letters/new
  # GET /letters/new.json
  def new
    @letter = Letter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @letter }
    end
  end

  # GET /letters/1/edit
  def edit
    @letter = Letter.find(params[:id])
  end

  # POST /letters
  # POST /letters.json
  def create
    
    
    @letter = Letter.new(letter_params)    
    respond_to do |format|
      if @letter.save
        if @letter.controller_name == 'main'
          # format.html { redirect_to edit_user_letter_path(current_user, @letter) }
          format.html { redirect_to edit_letter_path(@letter) }
        else
          format.html { redirect_to @letter, notice: '편지가 작성되었습니다.' }
          format.json { render json: @letter, status: :created, location: @letter }
        end
      else
        format.html { render action: "new" }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /letters/1
  # PUT /letters/1.json
  def update
    @letter = Letter.find(params[:id])

    respond_to do |format|
      if @letter.update_attributes(letter_params)
        # format.html { redirect_to @letter, notice: '편지가 작성되었습니다.' }
        format.html { redirect_to user_letter_path(current_user, @letter), notice: '편지가 작성되었습니다.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /letters/1
  # DELETE /letters/1.json
  def destroy
    @letter = Letter.find(params[:id])
    @letter.destroy

    respond_to do |format|
      format.html { redirect_to letters_url }
      format.json { head :no_content }
    end
  end
  
  private  
  
    def letter_params
      params.require(:letter).permit(:content, :receiver_name, :receiver_address, :receiver_phone, :sender_address, :sender_name, :sender_phone, :controller_name)
      
    end
  
end

app/controllers/user/letters_controller.rb
class User::LettersController < ApplicationController
  before_filter :store_location
  before_filter :require_login
  def index
    @user = current_user
    @letters = @user.letters
  end

  def new
    @letter = Letter.new
    @user = current_user

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @letter }
    end
  end
  
  def create
    @letter = Letter.new(letter_params)   
    @user = current_user 
    respond_to do |format|
      if @letter.save
        billing = @user.billings.create()
        billing.letters << @letter
        billing.save
        # if @letter.controller_name == 'main'
        #   format.html { redirect_to user_edit_letter_path(current_user, @letter), notice: '편지가 작성되었습니다.' }
        # else
          format.html { redirect_to edit_user_letter_path(current_user, @letter), notice: '편지가 작성되었습니다.' }
          format.json { render json: @letter, status: :created, location: @letter }
        # end
      else
        format.html { render action: "new" }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @user = current_user
    @letter = Letter.find(params[:id])
  end
  
  def update
    @letter = Letter.find(params[:id])
    @user = User.find(params[:user_id])
    @user.letters << @letter
    respond_to do |format|
      if @letter.update_attributes(letter_params)
        format.html { redirect_to user_letter_path(current_user, @letter), notice: '편지가 작성되었습니다.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def show
    @user = current_user
    @letter = Letter.find(params[:id])
    if @letter.user.nil?
      @letter.user = @user
      @letter.save
    end
    if @letter.billing.user.nil?
      billing = @letter.billing
      billing.user = @user
      billing.save
    end
  end
  
  private  
  
    def letter_params
      params.require(:letter).permit(:sender_name, :receiver_name, :sender_address, :receiver_address, :content)
    end
  
end

app/helpers/admin/letters_helper.rb
module Admin::LettersHelper
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/helpers/user/letters_helper.rb
module User::LettersHelper
end

app/views/letters/_form.html.slim
= simple_form_for(@letter) do |f|
  - if @letter.errors.any?
    #error_explanation
      h2
        = pluralize(@letter.errors.count, "error")
        | prohibited this letter from being saved:
      ul
        - @letter.errors.full_messages.each do |msg|
          li= msg
  div.panel
    div.form-group  
      = f.input :sender_name, label: "보내는 분 이름", input_html: {class: "form-control"}
    div.form-group  
      = f.input :receiver_name, label: "받는 분 이름", input_html: {class: "form-control"}
    div.form-group
      = f.input :sender_address, label: "보내는 분 주소", input_html: {class: "form-control"}
    div.form-group
      = f.input :receiver_address, label: "받는 분 주소", input_html: {class: "form-control"}
    div.form-group
      = f.input :content, label: "전할 이야기", as: :text, input_html: {class: "form-control"}
    div.form-group
      = f.submit '확인하기!', class: "form-control btn btn-default", id: "submit"

app/views/letters/edit.html.slim
/! Fixed navbar
.container
  /! Main component for a primary marketing message or call to action
  .jumbotron
    h1 편지 보내기 2단계
    p 
      | 편지를 보내는 데 필요한 나머지를 알려주세요. 친구에게 보내는 편지가 잘 도착하기 위해서 필요합니다. 우편번호 필요없이 주소만 적어주시면, 우편번호는 저희가 찾아드릴께요 ^^
    / p
    /   a.btn.btn-large.btn-primary href="../../docs/#navbar"
  = render 'form'

app/views/letters/new.html.slim
/! Fixed navbar
.container
  /! Main component for a primary marketing message or call to action
  .jumbotron
    h1 아날로그 기프티콘 커피레터
    p 
      | 약봉투에 담긴 신선한 핸드 드립용 커피빈 3봉지, 일회용 드립퍼 3장, 필터 3장. 그리고 친구에게 전하고 싶은 당신의 이야기. 커피레터로 전하세요.
    / p
    /   a.btn.btn-large.btn-primary href="../../docs/#navbar"
  = render 'form'

app/views/letters/show.html.slim
.container
  .jumbotron
    h1 편지 쓰기 마지막 단계!
    p 
      |  받는 분 성함과 주소를 다시 한 번 확인 부탁드려요. 전할 이야기도 한 번 다시 확인해보시구요. 혹시 주소가 틀리다면 저희가 전화로 다시 여쭤볼께요. 보내시는 분 성함과 전화번호도 확인 부탁드려요^^
  ul.list-group
    li.list-group-item
      dl
        dt 받는 분 이름
        dd = @letter.receiver_name
    li.list-group-item
      dl
        dt 받는 분 주소
        dd = @letter.receiver_address
    li.list-group-item
      dl
        dt 전할 이야기
        dd = @letter.content
    li.list-group-item
      dl
        dt 보내는 분 이름
        dd = @letter.sender_name
    li.list-group-item
      dl
        dt 보내는 분 주소
        dd = @letter.sender_address
  ul.nav class="nav-pills"
    li.active
      = link_to '우표 붙이기!', edit_billing_path(@letter.billing)
    li
      = link_to '다시 고치기!', edit_letter_path(@letter)
    / li
    /   = link_to '일단 저장하고 다음에 보내기^^7', edit_letter_path(@letter)