config/routes.rb
CoffeeLetter::Application.routes.draw do

  get "users/index"
  get "dashboard/index"

  get "signup"  => "users#new", :as => "signup"
  get "logout"  => "sessions#destroy", :as => "logout"
  get "login"   => "sessions#new", :as => "login"
  match 'admin' => 'admin/dashboard#index', :via => :get, :as => "admin" 
  
  resources :users, :only => [:create, :new]
  resources :sessions
  resources :letters, except: [:destroy, :index]
  resources :billings

  namespace :admin do
    resources :dashboard, only: [:index]
    resources :letters
    resources :billings, except: [:destroy]
    resources :users, except: [:destroy]
    resources :coupons, except: [:destroy]
    resources :products, except: [:destroy]
  end

  resources :users do
    scope module: :user do 
      resources :letters, except: [:destroy]
      resources :billings, except: [:destroy, :new]
      resources :main, only: [:index]
    end
  end

  get "main/index"
  root :to => 'main#index'
end

app/models/billing.rb
class Billing < ActiveRecord::Base
  has_one :letter
  belongs_to :coupon
  belongs_to :product
  belongs_to :user
  accepts_nested_attributes_for :letter
  
  before_create :billing_has_default_product
  
  def use_coupon_code(code)
    if self.user.nil?
      result = Coupon.valid?(code)
      if result == true
        coupon = Coupon.find_by(code: code)
        self.activate_coupon(coupon)
      end
    else
      result = Coupon.valid?(code, self.user)
      if result == true
        self.activate_coupon(coupon)
      elsif result.class == Integer
        
      end
    end
  end
  
  def use_coupon(coupon)
    
  end
  
  def activate_coupon(coupon)
    self.coupon = coupon
    discount_value = self.coupon.discount_value
    unless self.coupon.discount_value.nil?  
      if self.coupon.discount_value > 1.0
        self.sale_price = (self.sale_price - discount_value).to_i
      elsif self.coupon.discount_value <= 1.0
        self.sale_price = (self.sale_price - (discount_value * price)).to_i
      end
    end
    self.total_price = self.sale_price * self.amount
    self.coupon.status = "used"
    self.save
  end
  
  private
    def create_or_find_default_product
      if Product.exists?(title: "default_product")
        Product.where(title: "default_product").last
      else
        Product.create(title: "default_product", price: 3400, discount_value: 0.1)
      end
    end
    
    def billing_has_default_product
      self.product = create_or_find_default_product
      price = self.product.price
      discount_value = self.product.discount_value
      
      self.amount = 1
      self.price = price
      unless self.product.discount_value.nil?  
        if self.product.discount_value > 1.0
          self.sale_price = (price - discount_value).to_i
        elsif self.product.discount_value <= 1.0
          self.sale_price = (price - (discount_value * price)).to_i
        end
      else
        self.sale_price = price
      end
      self.total_price = self.sale_price * self.amount
    end
  
end

app/controllers/admin/billings_controller.rb
class Admin::BillingsController < ApplicationController
  layout 'admin'
  def index
    @billings = Billing.all
  end

  def show
  end

  def edit
  end
end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController
  before_filter :store_location
  before_filter :require_login, only: [:show, :new, :edit]
  # GET /billings
  # GET /billings.json
  def index
    @billings = Billing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @billings }
    end
  end

  # GET /billings/1
  # GET /billings/1.json
  def show
    
    @billing = Billing.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @billing }
    end
  end

  # GET /billings/new
  # GET /billings/new.json
  def new
    @letter = Letter.new
    @letter.billings.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @billing }
    end
  end

  # GET /billings/1/edit
  def edit
    # @letter = Letter.find(params[:id])
    redirect_to edit_user_billing_path(current_user.id, @letter.id)
  end

  # POST /billings
  # POST /billings.json
  def create
    @billing = Billing.new(params[:billing])

    respond_to do |format|
      if @billing.save
        format.html { redirect_to @billing, notice: 'Billing was successfully created.' }
        format.json { render json: @billing, status: :created, location: @billing }
      else
        format.html { render action: "new" }
        format.json { render json: @billing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /billings/1
  # PUT /billings/1.json
  def update
    @billing = Billing.find(params[:id])

    respond_to do |format|
      if @billing.update_attributes(params[:billing])
        format.html { redirect_to @billing, notice: 'Billing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @billing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /billings/1
  # DELETE /billings/1.json
  def destroy
    @billing = Billing.find(params[:id])
    @billing.destroy

    respond_to do |format|
      format.html { redirect_to billings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/user/billings_controller.rb
#encoding: utf-8
class User::BillingsController < ApplicationController
  before_filter :require_login
  def index
    @user = User.find(params[:user_id])
    @billings = @user.billings
  end

  def new
    @user = User.find(params[:user_id])
    @billing = Billing.new
  end

  def edit
    @user = User.find(params[:user_id])
    @billing = Billing.find(params[:id])
  end
  
  def show
    @user = User.find(params[:user_id])
    @billing = Billing.find(params[:id])
    @letter = @billing.letter
  end
  
  def update
    @billing = Billing.find(params[:id])
    respond_to do |format|
      if @billing.update_attributes(billing_params)
        format.html { redirect_to user_billing_path(current_user, @billing), notice: '입금정보가 작성되었습니다.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @billing.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private
  
    def billing_params
      params.require(:billing).permit(:sender_name, :sender_phone) 
    end
  
end

app/helpers/admin/billings_helper.rb
module Admin::BillingsHelper
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/user/billings_helper.rb
module User::BillingsHelper
end

app/views/billings/_form.html.slim
.panel
  = simple_form_for @letter do |f|
    = f.simple_fields_for :billings do |billing_form|
      .form-group
        = billing_form.input :sender_name, label: "입금자 성명", input_html: {class: "form-control", value: @letter.sender_name}
    .form-group
      = f.input :sender_phone, label: "입금 확인 문자 받을 전화번호", input_html: {class: "form-control"}
    .form-group
      = f.input :email, label: "배송 정보 확인 로그인용 이메일", input_html: {class: "form-control"}
    .form-group
      = f.input :email, label: "배송 정보 확인 로그인용 비밀번호", input_html: {class: "form-control"}
    .form-group
      = f.submit '신청 완료', class: "form-control btn btn-default"

app/views/billings/edit.html.slim
.container
  p#notice= notice
  .jumbotron
    h1 우표 붙이기
    p
      | 친구에게 편지를 보내기 위해  
      =default_price
      |을 아래 계좌번호로 입금해주세요. (우송비 포함 가격입니다.)
    p=account_for_customer
  = render 'form'

app/views/billings/index.html.slim
h1 Listing billings

table
  tr
  - @billings.each do |billing|
    tr
      td = billing.letters.first.sender_name unless billing.letters.first.nil?
      td = billing.amount
      td = billing.approved_at
      td = billing.status
      td = billing.status_desc
      td = billing.sender_name

br

= link_to 'New Billing', new_billing_path

app/views/billings/new.html.slim
.container
  p#notice= notice
  .jumbotron
    h1 우표 붙이기
    p
      | 친구에게 편지를 보내기 위해  
      =default_price
      |을 아래 계좌번호로 입금해주세요. 
    p=account_for_customer
  = render 'form'

app/views/billings/show.html.slim
.container
  .jumbotron
    h1 이제 곧 커피레터가 친구에게 발송됩니다.
    p 
      span 
      |커피레터 발송비 
      =default_price
      |을 
      span=account_for_customer
      span 으로 입금해주세요.
  ul.list-up
    li.list-group-item
      dl
        dt 받는 분 이름
        dd 
    li.list-group-item
      dl
        dt 받는 분 주소
        dd 
    li.list-group-item
      dl
        dt 전할 이야기
        dd 
    li.list-group-item
      dl
        dt 보내는 분 이름
        dd 
    li.list-group-item
      dl
        dt 보내는 분 주소
        dd 
  ul.nav class="nav-pills"
    li.active
      = link_to '우표 붙이기!'
    li
      = link_to '다시 고치기!' 